spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345

  # 其他请求方法需要打开
  mvc:
    static-path-pattern: /mm/**

  hiddenmethod:
    filter:
      enabled: true